spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forSpring
    username: postgres
    password: 1899
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: "srighrgrdhbgkjhrghjbgsdbrdhjbgrjkbgrjgjtgkbrgbgjkjbgfb"

